name: auto build engine

on: 
  release:
    types: [Testing]
  push:
    branches: 
      - linux-msft-wsl-5.15.y
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Install build depedencies
      run: |
        sudo apt update
        sudo apt install -y flex bison libelf-dev dwarves
    
    - name: Bulid kernel
      run: |
        #git clone https://github.com/torvalds/linux.git --depth 1 linux
        #git clone https://github.com/microsoft/WSL2-Linux-Kernel --depth 1 linux
        git clone https://github.com/torvalds/linux.git -o v5.15 --depth 1 linux
        #git clone https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-rt-devel.git -b for-kbuild-bot/current-stable --depth 1 linux
        wget --no-check-certificate https://raw.githubusercontent.com/ActiveIce/WSL2-Linux-Kernel/master/dxgkrnl.patch
        pushd linux
        git apply ../dxgkrnl.patch --reject
        sed -i '13s/$/#define _MAIN_KERNEL_/' ./drivers/hv/dxgkrnl/dxgkrnl.h
        wget --no-check-certificate -P Microsoft https://github.com/arunkanth9/WSL2-Linux-Kernel/blob/linux-msft-wsl-5.15.y/Microsoft/config-wsl
        echo 'CONFIG_X86_KERNEL_IBT=n' >> Microsoft/config-wsl
        #scripts/config --disable PREEMPT_NONE
        #scripts/config --enable PREEMPT_RT
        make -j$(nproc) KCONFIG_CONFIG=Microsoft/config-wsl LOCALVERSION=""
        popd

    - name: Upload kernel
      uses: actions/upload-artifact@master
      with:
        name: bzImage
        path: linux/arch/x86/boot/bzImage

  push:
    needs: build
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Download kernel
      uses: actions/download-artifact@master
      with:
        name: bzImage
        path: ./
    
   
